---
- name: "Installing ntp"
  pacman:
    name: ntp
    update_cache: yes

- name: "Installing ntp config"
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - etc/ntp.conf
  notify:
    - restart ntpd
