---
- name: "Installing ntp"
  apt:
    name: [ ntp, ntpdate ]
    update_cache: yes

- name: "Installing ntp config"
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - etc/ntp.conf


# vim: tabstop=2 shiftwidth=2 expandtab
