---
- name: "Installing packages for autofs"
  apt:
    name: [cifs-utils, netcat-traditional, smbclient, dnsutils, autofs]
    update_cache: yes

- name: "Copy /etc/krb5.conf"
  copy:
    src: etc/krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: "Copy /etc/request-key.d/cifs.idmap.conf"
  copy:
    src: etc/request-key.d/cifs.idmap.conf
    dest: /etc/request-key.d/cifs.idmap.conf
    owner: root
    group: root
    mode: 0644

- name: "Copy /etc/request-key.d/cifs.spnego.conf"
  copy:
    src: etc/request-key.d/cifs.spnego.conf
    dest: /etc/request-key.d/cifs.spnego.conf
    owner: root
    group: root
    mode: 0644

- name: "Create dir /dfs/empa.emp-eaw.ch"
  file:
    path: /dfs/empa.emp-eaw.ch
    owner: root
    group: root
    mode: 0755
    state: directory

- name: "Create dir /dfs/.empa.emp-eaw.ch"
  file:
    path: /dfs/.empa.emp-eaw.ch
    owner: root
    group: root
    mode: 0755
    state: directory

- name: "Create link /dfs/empa.emp-eaw.ch/data"
  file:
    src: /dfs/.empa.emp-eaw.ch/data
    dest: /dfs/empa.emp-eaw.ch/data
    state: link
    force: yes
    follow: false

- name: "Copy /etc/auto.data"
  copy:
    src: etc/auto.data
    dest: /etc/auto.data
    owner: root
    group: root
    mode: 0755
  notify:
    - restart autofs

- name: "Copy /etc/auto.master"
  copy:
    src: etc/auto.master
    dest: /etc/auto.master
    owner: root
    group: root
    mode: 0644
  notify:
    - restart autofs

- name: "Create dir /etc/skel/.config/gtk-3.0"
  file:
    path: /etc/skel/.config/gtk-3.0
    owner: root
    group: root
    mode: 0755
    state: directory

- name: "Copy /etc/skel/.config/gtk-3.0/bookmarks for autofs"
  copy:
    src: etc/skel/.config/gtk-3.0/bookmarks
    dest: /etc/skel/.config/gtk-3.0/bookmarks
    owner: root
    group: root
    mode: 0644

- name: "Create link /etc/skel/DFS"
  file:
    src: /dfs/empa.emp-eaw.ch/data
    dest: /etc/skel/DFS
    state: link
    force: yes
    follow: false
    
- name: Ensure autofs is running (and enable at boot)
  service:
    name: autofs
    state: started
    enabled: yes

- meta: flush_handlers

# vim: tabstop=2 shiftwidth=2 expandtab
