---
- name: "Configuring ansible"
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root 
    group: root 
    mode: 0644
  with_items:
    - etc/ansible/ansible.cfg

# vim: tabstop=2 shiftwidth=2 expandtab
