---
- name: "Installing Kerberos and dependecies"
  pacman:
    name: [ krb, pam-krb5 ]
    update_cache: yes

# This requires the plugin 'ansible-aur'. See README.md
- name: "Installing 'realmd' from AUR"
  aur: name=realmd use=makepkg skip_installed=true
  become: yes
  become_user: aur_builder # required because AUR helpers forbid executing makepkg and related operations as root
