---
- name: "Installing sudo"
  pacman:
    name: sudo
    update_cache: yes

- name: "Allow sudo for 'wheel' users"
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root 
    group: root 
    mode: 0644
    force: no
    validate: /usr/bin/visudo -csf %s
  with_items:
    - etc/sudoers.d/wheel-users
  notify:
    - create aur_builder
    - allow aur_builder to sudo
