---
- name: create aur_builder
  user:
    name: aur_builder
    group: wheel

  lineinfile:
    path: /etc/sudoers.d/11-install_aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
		create: yes
		validate: 'visudo -cf %s'
